### ISSUE TITLE
Confusing steps in "How to Install and Use Your BitcoinDark-QT Wallet.pdf"

### ISSUE THREAD

**Issue by Tset-Noitamotua** [jl777/btcd#66]
I am trying to follow the LINUX BUILD steps in 

http://bitcoindark.com/docs/How%20to%20Install%20and%20Use%20Your%20BitcoinDark-QT%20Wallet.pdf

on Ubuntu 17.04

Steps 1 to 10 are working fine. From step 11 things become confusing

> 11) go to bitcoindark folder and double-click bitcoindark-qt.exe to launch client
> 12) go to home folder and press Ctrl+H to show hidden files
> 13) open hidden .Bitcoindark folder in order to access your wallet.dat file
> ...
>16) change "user" and "pass" in BitcoinDark.conf file to something unique and save it

e.g. step 11 --> `double-click bitcoindark-qt.exe` ? .exe on Linux?

Could you please review and update the steps?

Cheers
Tset

**Comment by jl777** [comment]
BTCD is not supported anymore, KMD is the new BTCD

**Comment by Tset-Noitamotua** [comment]
thanks for clarification

you have no issue tracker activated in komodo repo :(
